<?php

namespace App\Validations;

use App\Exceptions\BadRequestException;

class TasksValidator
{
    const RULES = [
        'task' => 'required|max:255',
        'status' => 'required|in:pending,started,done'
    ];

    const MESSAGES = [
        'task.required' => 'Campo tarefa obrigat칩rio.',
        'task.max' => 'A tarefa deve ter no m치ximo 255 caracteres.',
        'status.required' => 'Status da tarefa obrigat칩rio.',
        'status.in' => 'Status da tarefa inv치lido.'
    ];

    /**
     * @throws BadRequestException
     */
    public static function validate ($task, $status): void
    {
        $validator = validator([
            'task' => $task,
            'status' => $status
        ], self::RULES, self::MESSAGES);

        if ($validator->fails()) {
            throw new BadRequestException($validator->getMessageBag()->first(), $validator);
        }
    }
}
